# Site settings
title: Tim Wisniewski
email: tim@timwis.com
description: Civic technologist specialising in navigating bureaucracy, culture change, and outside-the-box problem solving.
baseurl: "" # the subpath of your site, e.g. /blog/

exclude:
  - data-scripts

# Collections
collections:
  - projects

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
