# Site settings
title: Tim Wisniewski
email: tim@timwis.com
description: Chief Data Officer for the City of Philadelphia
baseurl: "" # the subpath of your site, e.g. /blog/

# Collections
collections:
  - projects

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown
